// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPFjq683u55zuHoXtqhjXkgGQq48DrWgc',
    appId: '1:850237205872:web:fb2ab4aa56345eeede33b5',
    messagingSenderId: '850237205872',
    projectId: 'salespro-3375d',
    authDomain: 'salespro-3375d.firebaseapp.com',
    storageBucket: 'salespro-3375d.firebasestorage.app',
    measurementId: 'G-HHS8NY7KLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDCJNkTHpaUVX17ZD4lTayJi2vbyrqP44',
    appId: '1:850237205872:android:8dcefa5440943aa7de33b5',
    messagingSenderId: '850237205872',
    projectId: 'salespro-3375d',
    storageBucket: 'salespro-3375d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUqMNpqldd1aTZvr36V-O1BVjhG-xayHU',
    appId: '1:850237205872:ios:c69b5101df6f52e3de33b5',
    messagingSenderId: '850237205872',
    projectId: 'salespro-3375d',
    storageBucket: 'salespro-3375d.firebasestorage.app',
    iosBundleId: 'com.example.salespro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUqMNpqldd1aTZvr36V-O1BVjhG-xayHU',
    appId: '1:850237205872:ios:c69b5101df6f52e3de33b5',
    messagingSenderId: '850237205872',
    projectId: 'salespro-3375d',
    storageBucket: 'salespro-3375d.firebasestorage.app',
    iosBundleId: 'com.example.salespro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPFjq683u55zuHoXtqhjXkgGQq48DrWgc',
    appId: '1:850237205872:web:3bddad51ae65625bde33b5',
    messagingSenderId: '850237205872',
    projectId: 'salespro-3375d',
    authDomain: 'salespro-3375d.firebaseapp.com',
    storageBucket: 'salespro-3375d.firebasestorage.app',
    measurementId: 'G-YJFSGL6L45',
  );
}
